package com.rzmmzdh.toro.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0556CF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDAE2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001847)
val md_theme_light_secondary = Color(0xFF984061)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onSecondaryContainer = Color(0xFF3E001D)
val md_theme_light_tertiary = Color(0xFF466811)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC6F08A)
val md_theme_light_onTertiaryContainer = Color(0xFF112000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF330045)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF330045)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF757780)
val md_theme_light_inverseOnSurface = Color(0xFFFFEBFF)
val md_theme_light_inverseSurface = Color(0xFF4D1661)
val md_theme_light_inversePrimary = Color(0xFFB2C5FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0556CF)

val md_theme_dark_primary = Color(0xFFB2C5FF)
val md_theme_dark_onPrimary = Color(0xFF002C72)
val md_theme_dark_primaryContainer = Color(0xFF0040A0)
val md_theme_dark_onPrimaryContainer = Color(0xFFDAE2FF)
val md_theme_dark_secondary = Color(0xFFFFB1C8)
val md_theme_dark_onSecondary = Color(0xFF5E1133)
val md_theme_dark_secondaryContainer = Color(0xFF7B2949)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_tertiary = Color(0xFFABD471)
val md_theme_dark_onTertiary = Color(0xFF213600)
val md_theme_dark_tertiaryContainer = Color(0xFF314F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFC6F08A)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF330045)
val md_theme_dark_onBackground = Color(0xFFFAD7FF)
val md_theme_dark_surface = Color(0xFF330045)
val md_theme_dark_onSurface = Color(0xFFFAD7FF)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_outline = Color(0xFF8F9099)
val md_theme_dark_inverseOnSurface = Color(0xFF330045)
val md_theme_dark_inverseSurface = Color(0xFFFAD7FF)
val md_theme_dark_inversePrimary = Color(0xFF0556CF)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB2C5FF)


val seed = Color(0xFF0757D0)